<a href="https://colab.research.google.com/github/rohitthapar/Sampling/blob/main/SamplingAssignment_102003482_RohitThapar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Submission by:
Puranjay Singh <br>
102003384 <br>
3CO9

In [299]:
import numpy as np
import pandas as pd
df = pd.read_csv(r'C:\Users\purja\Downloads/Creditcard_data.csv')

In [300]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,1
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [301]:
df['Class'].value_counts()

0    763
1      9
Name: Class, dtype: int64

In [302]:
class_count = df["Class"].value_counts(normalize=False)
print(class_count)

0    763
1      9
Name: Class, dtype: int64

In [303]:
X = df.drop(['Class','Time'], axis=1) #also dropping Time attribute as it is not a helpful feature
Y = df['Class']

# Balancing the imbalanced dataset:
## Random oversampling has been used to balance the imbalanced dataset. Random oversampling involves randomly duplicating examples from the minority class and adding them to the training dataset.

In [304]:
from imblearn.over_sampling import RandomOverSampler
randoversam = RandomOverSampler(random_state=42)
X_r, Y_r = randoversam.fit_resample(X, Y)

In [305]:
class_count_new = Y_r.value_counts(normalize=False)
print(class_count_new)

0    763
1    763
Name: Class, dtype: int64

In [306]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_r, Y_r, test_size=0.33, random_state=42)

In [307]:
df_new = pd.concat([X_r, Y_r], axis=1)
df_new

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,1
2,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1521,-2.000567,-2.495484,2.467149,1.140053,2.462010,0.594262,-2.110183,0.788347,0.958809,-0.328631,...,0.422452,1.195394,0.297836,-0.857105,-0.219322,0.861019,-0.124622,-0.171060,1.50,1
1522,0.073497,0.551033,0.451890,0.114964,0.822947,0.251480,0.296319,0.139497,-0.123050,-0.142617,...,-0.128758,-0.381932,0.151012,-1.363967,-1.389079,0.075412,0.231750,0.230171,0.99,1
1523,0.073497,0.551033,0.451890,0.114964,0.822947,0.251480,0.296319,0.139497,-0.123050,-0.142617,...,-0.128758,-0.381932,0.151012,-1.363967,-1.389079,0.075412,0.231750,0.230171,0.99,1
1524,-1.738582,0.052740,1.187057,-0.656652,0.920623,-0.291788,0.269083,0.140631,0.023464,-0.066407,...,-0.179545,-0.192036,-0.261879,-0.237477,-0.335040,0.240323,-0.345129,-0.383563,1.00,1
1525,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,-0.838587,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.00,1

## The five models that have been used for analysis are:
1. Random forest
2. Decision tree
3. Logistic Regression
4. SVC
5. K-Nearest Neighbors 

Corresponding functions have been defined that fit the dataset into the model, make predictions and return accuracy which is then used for final comparison.

In [308]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [309]:
def RandomForest(X_train, Y_train, X_test, Y_test):
    clf = RandomForestClassifier(n_estimators = 2)
    clf.fit(X_train, Y_train)
    Y_pred = clf.predict(X_test)
    return accuracy_score(Y_test,Y_pred)

In [310]:
def KNN(X_train, Y_train, X_test, Y_test):
    knn = KNeighborsClassifier(n_neighbors = 7).fit(X_train, Y_train)
    Y_pred = knn.predict(X_test)
    return accuracy_score(Y_test,Y_pred)

In [311]:
def DecisionTree(X_train, Y_train, X_test, Y_test):
    tree = DecisionTreeClassifier(max_depth = 2).fit(X_train, Y_train)
    Y_pred = tree.predict(X_test)
    return accuracy_score(Y_test,Y_pred)

In [312]:
def Logistic(X_train, Y_train, X_test, Y_test):
    clf = LogisticRegression()
    clf.fit(X_train, Y_train)
    Y_pred = clf.predict(X_test)
    return accuracy_score(Y_test,Y_pred)

In [313]:
def SVC(X_train, Y_train, X_test, Y_test):
    svm = SGDClassifier(loss='hinge')
    svm.fit(X_train, Y_train)
    Y_pred = svm.predict(X_test)
    return accuracy_score(Y_test,Y_pred)

# The five sampling techniques have been used as follows: 
## 1. Simple random sampling

In [314]:
import math
import random as rd
z = 1.96 #confidence level
p = 0.5
e = 0.05 #margin of error
n_srs = math.floor((z*z*p*(1-p))/(e*e))
print("n = ", n_srs)
def random_sampling(df, n_srs):
    random_sample = df.sample(n = n_srs)
    return(random_sample)

randomSample = random_sampling(df_new, n_srs)

n =  384

In [315]:
randomSample.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
610,-2.400261,-1.383754,1.610151,-2.452649,-0.592392,-0.041593,-0.554247,0.090479,-1.852860,1.689143,...,-0.223480,0.484416,0.318866,-0.326228,0.587978,-0.126954,0.123830,0.485189,79.00,0
550,-0.566531,-0.057728,-0.825121,-1.040222,1.059728,3.811274,0.066048,1.280204,-0.504435,-0.673690,...,0.208875,-0.046195,0.567673,1.039253,-0.371477,0.997043,-0.198837,-0.019047,235.70,0
352,-0.363608,1.104008,1.300678,0.070314,0.075180,-1.010396,0.683396,-0.073378,-0.401866,-0.508233,...,-0.261158,-0.685436,-0.013662,0.336313,-0.157577,0.071699,0.245539,0.099037,0.99,0
784,0.073497,0.551033,0.451890,0.114964,0.822947,0.251480,0.296319,0.139497,-0.123050,-0.142617,...,-0.128758,-0.381932,0.151012,-1.363967,-1.389079,0.075412,0.231750,0.230171,0.99,1
649,1.196288,0.217099,0.402596,0.921664,-0.252045,-0.392240,-0.047177,0.041339,-0.069318,0.169913,...,-0.205751,-0.688869,0.054388,-0.056469,0.352684,-0.625998,0.013681,0.015683,9.99,0

In [316]:
X_srs = randomSample.drop('Class', axis=1) #new training X
Y_srs = randomSample['Class'] #new training Y

SRS_RandomForest = RandomForest(X_srs,Y_srs,X_test,Y_test)
SRS_DecisionTree = DecisionTree(X_srs,Y_srs,X_test,Y_test)
SRS_KNN = KNN(X_srs,Y_srs,X_test,Y_test)
SRS_Logistic = Logistic(X_srs,Y_srs,X_test,Y_test)
SRS_svc = SVC(X_srs,Y_srs,X_test,Y_test)

SRS = [SRS_RandomForest,SRS_DecisionTree,SRS_KNN,SRS_Logistic,SRS_svc]
print(SRS)

[0.996031746031746, 0.9305555555555556, 0.9305555555555556, 0.9126984126984127, 0.8253968253968254]

C:\Users\purja\Desktop\sample_project_1\env\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

## 2. Stratified Sampling

In [317]:
s = 2 #number of strata
n_strat = math.floor((z*z*p*(1-p))/(e*e/s*s))
print("n = " , n_strat)
strata = df_new.groupby('Class')

stratifiedSample = strata.apply(lambda x: x.sample(n_strat))

n =  384

In [318]:
stratifiedSample.head()

                 V1        V2        V3        V4        V5        V6  \
Class
0     473 -0.343986  0.539789  1.024662 -0.371899  1.037336  1.261849
      680  0.166862  1.667709 -2.095559  1.835206  0.876545 -1.481721
      698 -0.378417  0.751515  1.772256  0.311020 -0.329130 -0.746206
      494 -0.456586  0.541708  1.331297  0.559447  0.184045  0.612792
      764 -1.062129 -0.618574  0.615388 -3.335834  0.746649 -0.540531

                 V7        V8        V9       V10  ...       V21       V22  \
Class                                              ...
0     473  0.473409  0.227169  0.248279 -0.086236  ... -0.111901  0.170232
      680 -0.323575 -2.866382 -0.573338 -1.838310  ... -1.383098  0.207549
      698  0.719034 -0.081805 -0.152417 -0.661177  ... -0.120891 -0.240394
      494  0.632759  0.152253 -0.202196 -0.510699  ... -0.134465 -0.316126
      764  0.705932  0.032525  1.334181 -2.326389  ... -0.114269 -0.661122

                V23       V24       V25       V26       V27       V28  Amount  \
Class
0     473 -0.415083 -1.659553 -0.054849  0.455438  0.201538 -0.054236    3.99
      680  0.550348 -0.006635 -0.554034 -0.421468  0.007827 -0.039904    1.00
      698 -0.057803  0.733812 -0.049448  0.207357  0.023386  0.057469   25.41
      494 -0.072149 -0.749725 -0.039644  0.472098  0.075612  0.099985   74.22
      764  0.136250 -1.377245  0.263820 -1.115516  0.079213  0.116638  131.37

           Class
Class
0     473      0
      680      0
      698      0
      494      0
      764      0

[5 rows x 30 columns]

In [319]:
X_st = stratifiedSample.drop('Class', axis=1) 
Y_st = stratifiedSample['Class'] 

ST_RandomForest = RandomForest(X_st,Y_st,X_test,Y_test)
ST_DecisionTree = DecisionTree(X_st,Y_st,X_test,Y_test)
ST_KNN = KNN(X_st,Y_st,X_test,Y_test)
ST_Logistic = Logistic(X_st,Y_st,X_test,Y_test)
ST_svc = SVC(X_st,Y_st,X_test,Y_test)

ST = [ST_RandomForest,ST_DecisionTree,ST_KNN,ST_Logistic,ST_svc]
print(ST)

[0.996031746031746, 0.9365079365079365, 0.9523809523809523, 0.9186507936507936, 0.9365079365079365]

C:\Users\purja\Desktop\sample_project_1\env\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

## 3. Cluster Sampling

In [320]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=10, random_state=42).fit(df_new) #number of clusters = 10
cluster_assignments = kmeans.labels_
cluster = [1,3,5,6,8]
cluster_series = pd.Series(cluster_assignments)

cluster_df = df_new[cluster_series.isin(cluster)]

In [321]:
cluster_df.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
2,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
8,-0.894286,0.286157,-0.113192,-0.271526,2.669599,3.721818,0.370145,0.851084,-0.392048,-0.410430,...,-0.073425,-0.268092,-0.204233,1.011592,0.373205,-0.384157,0.011747,0.142404,93.20,0
12,1.249999,-1.221637,0.383930,-1.234899,-1.485419,-0.753230,-0.689405,-0.227487,-2.094011,1.323729,...,-0.231809,-0.483285,0.084668,0.392831,0.161135,-0.354990,0.026416,0.042422,121.50,0

In [322]:
X_c = cluster_df.drop('Class', axis=1) 
Y_c = cluster_df['Class'] 

C_RandomForest = RandomForest(X_c,Y_c,X_test,Y_test)
C_DecisionTree = DecisionTree(X_c,Y_c,X_test,Y_test)
C_KNN = KNN(X_c,Y_c,X_test,Y_test)
C_Logistic = Logistic(X_c,Y_c,X_test,Y_test)
C_svc = SVC(X_c,Y_c,X_test,Y_test)

C = [C_RandomForest,C_DecisionTree,C_KNN,C_Logistic,C_svc]
print(C)

[0.5376984126984127, 0.5337301587301587, 0.5337301587301587, 0.5238095238095238, 0.45634920634920634]

C:\Users\purja\Desktop\sample_project_1\env\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

## 4. Systematic Sampling

In [323]:
interval = 3 #number of intervals
systematic_df = df_new.iloc[::interval]

In [324]:
systematic_df.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
3,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
6,1.229658,0.141004,0.045371,1.202613,0.191881,0.272708,-0.005159,0.081213,0.464960,-0.099254,...,-0.167716,-0.270710,-0.154104,-0.780055,0.750137,-0.257237,0.034507,0.005168,4.99,0
9,-0.338262,1.119593,1.044367,-0.222187,0.499361,-0.246761,0.651583,0.069539,-0.736727,-0.366846,...,-0.246914,-0.633753,-0.120794,-0.385050,-0.069733,0.094199,0.246219,0.083076,3.68,0
12,1.249999,-1.221637,0.383930,-1.234899,-1.485419,-0.753230,-0.689405,-0.227487,-2.094011,1.323729,...,-0.231809,-0.483285,0.084668,0.392831,0.161135,-0.354990,0.026416,0.042422,121.50,0

In [325]:
X_sy = systematic_df.drop('Class', axis=1) 
Y_sy = systematic_df['Class'] 

SY_RandomForest = RandomForest(X_sy,Y_sy,X_test,Y_test)
SY_DecisionTree = DecisionTree(X_sy,Y_sy,X_test,Y_test)
SY_KNN = KNN(X_sy,Y_sy,X_test,Y_test)
SY_Logistic = Logistic(X_sy,Y_sy,X_test,Y_test)
SY_svc = SVC(X_sy,Y_sy,X_test,Y_test)

SY = [SY_RandomForest,SY_DecisionTree,SY_KNN,SY_Logistic,SY_svc]
print(SY)

[0.996031746031746, 0.9345238095238095, 0.9365079365079365, 0.9146825396825397, 0.6448412698412699]

C:\Users\purja\Desktop\sample_project_1\env\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

## 5. Reservoir Sampling

In [326]:
def sample_reservoir(dataframe, sample_size, state = None):
    stream = []
    size = len(dataframe)
    for i in range(size):
        stream.append(i)
    i = 0
    reservoir = [0] * sample_size
    for i in range(sample_size):
        reservoir[i] = stream[i]
    rd.seed(state)
    while i < size:
        j = rd.randrange(i + 1)
        if j < sample_size:
            reservoir[j] = stream[i]
        i += 1
    
    return dataframe.iloc[reservoir]
reservoir_df = sample_reservoir(df_new, 400, 42)

In [327]:
reservoir_df.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
978,-2.000567,-2.495484,2.467149,1.140053,2.462010,0.594262,-2.110183,0.788347,0.958809,-0.328631,...,0.422452,1.195394,0.297836,-0.857105,-0.219322,0.861019,-0.124622,-0.171060,1.50,1
929,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,1
1428,-2.000567,-2.495484,2.467149,1.140053,2.462010,0.594262,-2.110183,0.788347,0.958809,-0.328631,...,0.422452,1.195394,0.297836,-0.857105,-0.219322,0.861019,-0.124622,-0.171060,1.50,1
805,1.257719,0.364739,0.306923,0.690638,-0.357792,-1.067481,0.094272,-0.210300,0.014455,-0.286012,...,-0.286856,-0.820658,0.127663,0.343128,0.221120,0.094391,-0.022189,0.030944,1.29,1
4,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [328]:
X_res = reservoir_df.drop('Class', axis=1)
Y_res = reservoir_df['Class']

R_RandomForest = RandomForest(X_res,Y_res,X_test,Y_test)
R_DecisionTree = DecisionTree(X_res,Y_res,X_test,Y_test)
R_KNN = KNN(X_res,Y_res,X_test,Y_test)
R_Logistic = Logistic(X_res,Y_res,X_test,Y_test)
R_svc = SVC(X_res,Y_res,X_test,Y_test)

R = [R_RandomForest,R_DecisionTree,R_KNN,R_Logistic,R_svc]
print(R)

[0.9940476190476191, 0.9206349206349206, 0.9305555555555556, 0.9285714285714286, 0.5634920634920635]

C:\Users\purja\Desktop\sample_project_1\env\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

## Comparing the final accuracies of all the models using datasets produced from different sampling techniques:

In [329]:
result_data = {
    'Model' : ['Random Forest','Decision Tree','K- Nearest Neighbor','Logistic Regression','SVC'],
    'Simple Random Sampling' : SRS,
    'Stratified Sampling' : ST,
    'Cluster Sampling' : C,
    'Systematic Sampling' : SY,
    'Reservoir Sampling' : R
}

In [330]:
result = pd.DataFrame(result_data)

# Final table:

In [331]:
result

,Model,Simple Random Sampling,Stratified Sampling,Cluster Sampling,Systematic Sampling,Reservoir Sampling
0,Random Forest,0.996032,0.996032,0.537698,0.996032,0.994048
1,Decision Tree,0.930556,0.936508,0.533730,0.934524,0.920635
2,K- Nearest Neighbor,0.930556,0.952381,0.533730,0.936508,0.930556
3,Logistic Regression,0.912698,0.918651,0.523810,0.914683,0.928571
4,SVC,0.825397,0.936508,0.456349,0.644841,0.563492

# Conclusion:

As clearly visible, Random forest Classifier is consistently working well in all the sampling techniques and producing the highest accuracy in most of the sampling methods.